### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/alukos/proj/pms-stub/my/app/-mix/my/alert/alert.js'

### ISSUE THREAD

**Issue by alukos** [nin-jin/pms#4]
Создал файлы в pms-stub/my:
```
$ npm start build my/app

> pms-stub@1.0.0 start /Users/alukos/proj/pms-stub
> pms "build" "my/app"

20:23:54 $jin.build..jsCompiled.pull 'jin/build/-mix/index.env=node.stage=release.js'
20:23:54  Building 'my/app?env=web&stage=test'
20:23:55 $jin.atom1.._fail Error: ENOENT: no such file or directory, open '/Users/alukos/proj/pms-stub/my/app/-mix/my/alert/alert.js' (/Users/alukos/proj/pms-stub/my/app/-mix/my/alert/alert.js)
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at jin_trait_instance.$jin.atom1.prop.$jin.file.base..content.pull (/Users/alukos/proj/pms-stub/jin/file/jin-file-base.env=node.jam.js:165:1)
    at jin_trait_instance.$jin.method.$jin.atom1.pullable..pull (/Users/alukos/proj/pms-stub/jin/atom1/pullable/jin-atom-pullable.jam.js:160:1)
    at jin_trait_instance.$jin.method.$jin.atom1.pullable..get (/Users/alukos/proj/pms-stub/jin/atom1/pullable/jin-atom-pullable.jam.js:116:1)
    at jin_trait_instance.$jin.method.$jin.atom1.getable..get (/Users/alukos/proj/pms-stub/jin/atom1/getable/jin-atom-getable.jam.js:7:1)

npm ERR! Darwin 13.4.0
...
```

**Comment by nin-jin** [comment]
Есть такое. Это баг в TS компиляторе - он по разному кладёт файлы. Необходимо, чтобы была хотя бы одна зависимость от другого пакета. Например, можно куда-нибудь добавить обращение к `$jin2_log`. Вскоре возьмусь за переписывание сборщика, чтобы подобных проблем не было.

**Comment by nin-jin** [comment]
Fixed.
